# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Unit Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode-deriveddata-
      
      - name: Select Latest Xcode
        run: |
          # サーバー内の最新Xcodeを探して設定
          LATEST_XCODE=$(ls /Applications | grep Xcode | sort -V | tail -1)
          echo "Using Xcode: $LATEST_XCODE"
          sudo xcode-select -s "/Applications/$LATEST_XCODE/Contents/Developer"
          
      - name: Run Tests
        run: |
          # 利用可能なシミュレーターを1つ自動取得して変数に入れる
          # DESTINATION=$(xcrun simctl list devices available | grep "iPhone" | head -1 | sed -e 's/ (.*//' -e 's/^[ \t]*//')
          # echo "Selected Destination: $DESTINATION"
          xcodebuild test \
            -project SwiftUI_YahooImageSearch_MVVM.xcodeproj \
            -scheme SwiftUI_YahooImageSearch_MVVM \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.2,arch=arm64' \
            -enableCodeCoverage YES \
            -quiet

          # 2. デフォルトの出力場所（DerivedData）からカバレッジを表示
          echo "--- Code Coverage Report ---"
          # 最新のテスト結果を探して表示するコマンド
          xcrun xccov view --report $(ls -td ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult | head -1)
