# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Unit Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        # 現在の最新安定版（Xcode 16系）を自動で選択させます
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
      - name: Run Tests
        run: |
          xcodebuild test \
            -project SwiftUI_YahooImageSearch_MVVM.xcodeproj \
            -scheme SwiftUI_YahooImageSearch_MVVM \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest'
