# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Unit Test

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        # 現在の最新安定版（Xcode 16系）を自動で選択させます
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
      - name: Run Tests
        run: |
          # 利用可能なシミュレーターを1つ自動取得して変数に入れる
          DESTINATION=$(xcrun simctl list devices available | grep "iPhone" | head -1 | sed -e 's/ (.*//' -e 's/^[ \t]*//')
          echo "Selected Destination: $DESTINATION"
          xcodebuild test \
            -project SwiftUI_YahooImageSearch_MVVM.xcodeproj \
            -scheme SwiftUI_YahooImageSearch_MVVM \
            -destination 'platform=iOS Simulator,name=$DESTINATION'
            -quiet
